# Runs the bluemira examples and checks for errors
name: bluemira_examples

on:
  workflow_dispatch:
  schedule:
    # Runs every Monday at 04:37
    - cron: "37 4 * * 1"

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bluemira
          environment-file: conda/environment.yml
          miniforge-version: "latest"
          use-only-tar-bz2: true
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install bluemira
        shell: bash -l {0}
        run: pip install -e .

      - name: Run examples
        shell: bash -l {0}
        run: |
          # Exclude examples using plasmod or process, as these aren't available
          # to the CI runners
          python ./scripts/run_examples.py \
            -e 'plasmod_example' \
            -e 'solver_example' \
            -e 'equilibria/fem_fixed_boundary' \
            -e 'codes/ext_code_script'
